### PR TITLE
add missing sip_remove_header()

### PR DESCRIPTION
**Pull request by guss77**
This is the counterpart to `sip_add_header()`

### CODE REVIEW

**Review by bklang — APPROVED** [review]

**Comment by bklang** [comment]
@guss77 Looks good! Would you mind also adding a test similar to the [one for sip_add_header](https://github.com/adhearsion/adhearsion-asterisk/blob/develop/spec/adhearsion/asterisk/call_controller_methods_spec.rb#L190)?

**Comment by lpradovera** [comment]
This is very nice, thank you!

**Review by benlangfeld — APPROVED** [review]
For extra points, an entry in the changelog would be lovely.

**Comment by guss77** [comment]
:+1:

**Comment by guss77** [comment]
Hey guys, I understand there's no activity on this repo? I'm cleaning up my stuff and would like to remove my fork with the PR, as I'm not using Adhearsion anymore.

If you still want to merge this PR, please do, otherwise I see no reason for me to maintain it.

**Review by benlangfeld — APPROVED** [review]

**Pull request merged**
